# Generated by Django 4.2.8 on 2024-01-07 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='description',
            field=models.TextField(max_length=1),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(max_length=1),
        ),
    ]
